Update OrangeFox-Recovery-Builder.yml

diff --git a/.github/workflows/OrangeFox-Recovery-Builder.yml b/.github/workflows/OrangeFox-Recovery-Builder.yml
--- a/.github/workflows/OrangeFox-Recovery-Builder.yml
+++ b/.github/workflows/OrangeFox-Recovery-Builder.yml
@@ -9,125 +9,216 @@ on:
         default: '12.1'
         type: choice
         options:
-          - 12.1
-          - 11.0
+        - 14.1
+        - 12.1
+        - 11.0
       DEVICE_TREE:
         description: 'Custom Recovery Tree'
         required: true
-        default: 'https://github.com/Seriousattempts/device_ums512_1h10'
+        default: 'https://github.com/kinguser981/android_device_xiaomi_marble-OFRP'
       DEVICE_TREE_BRANCH:
         description: 'Custom Recovery Tree Branch'
         required: true
-        default: 'main'
+        default: 'fox_12.1'
       DEVICE_PATH:
-        description: 'Device path'
+        description: 'Specify your device path.'
         required: true
-        default: 'device/sprd/ums512_1h10'
+        default: 'device/xiaomi/marble'
       DEVICE_NAME:
-        description: 'Device codename'
+        description: 'Specify your Device Codename.'
         required: true
-        default: 'ums512_1h10'
+        default: 'marble'
       BUILD_TARGET:
-        description: 'Build target'
+        description: 'Specify your Build Target'
         required: true
         default: 'recovery'
         type: choice
         options:
-          - boot
-          - recovery
-          - vendorboot
+        - boot
+        - recovery
+        - vendorboot
+      LDCHECK:
+        description: 'Path of blobs to check' 
+        required: true
+        default: 'system/bin/qseecomd'
+      RECOVERY_TAR:
+        description: 'Release recovery.tar For Samsung devices'
+        required: false
+        default: false
+        type: boolean
+      RECOVERY_INSTALLER:
+        description: 'Include recovery installer zip'
+        type: boolean
+        required: true
+        default: true
 
 jobs:
   build:
-    name: Build OrangeFox for ${{ github.event.inputs.DEVICE_NAME }}
+    name: Build OFRP by ${{ github.actor }}
     runs-on: ubuntu-latest
+    if: github.event.repository.owner.id == github.event.sender.id
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      BUILD_DATE: $(date +%Y%m%d)
-
+    permissions:
+      contents: write
     steps:
-    - name: Checkout Repository
-      uses: actions/checkout@v4
+    - name: Checkout
+      uses: actions/checkout@v3
 
-    - name: Set Up Build Environment
+    - name: Display Inputs
       run: |
-        sudo apt-get update
-        sudo apt-get install -y git-core gnupg flex bison build-essential zip \
-        curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev \
-        x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig
+        echo "::group::User Environment Variables"
+        echo "Displaying variables/inputs."
+        echo "Include Recovery Installer: ${{ github.event.inputs.RECOVERY_INSTALLER }}"
+        echo "Release recovery.tar For Samsung devices: ${{ github.event.inputs.RECOVERY_TAR }}"
+        echo "::endgroup::"
 
-    - name: Configure Git
-      run: |
-        git config --global user.name "GitHub Actions"
-        git config --global user.email "actions@github.com"
+    - name: Clean-up
+      uses: rokibhasansagar/slimhub_actions@main
 
-    - name: Initialize OrangeFox
+    - name: Swap Space
+      uses: pierotofy/set-swap-space@master
+      with:
+        swap-size-gb: 24
+      
+    - name: Build Environment
       run: |
-        mkdir -p OrangeFox
-        cd OrangeFox
-        repo init -u https://gitlab.com/OrangeFox/sync.git -b fox_${{ github.event.inputs.MANIFEST_BRANCH }}
-
-    - name: Sync Repository
+        sudo apt update
+        sudo apt -y upgrade
+        git clone https://gitlab.com/OrangeFox/misc/scripts
+        cd scripts
+        sudo bash setup/android_build_env.sh
+      
+    - name: Set-up Manifest
+      if: github.event.inputs.MANIFEST_BRANCH == '11.0' || github.event.inputs.MANIFEST_BRANCH == '12.1'
       run: |
-        cd OrangeFox
-        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
+        mkdir -p ${GITHUB_WORKSPACE}/OrangeFox
+        cd ${GITHUB_WORKSPACE}/OrangeFox
+        git config --global user.name "Samuel Kendall"
+        git config --global user.email "kinguser981@gmail.com"
+        git clone https://gitlab.com/OrangeFox/sync.git
+        cd sync
+        ./orangefox_sync.sh --branch ${{ github.event.inputs.MANIFEST_BRANCH }} --path ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}
 
     - name: Clone Device Tree
       run: |
-        cd OrangeFox/device
-        git clone ${{ github.event.inputs.DEVICE_TREE }} \
-          -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} \
-          ${{ github.event.inputs.DEVICE_PATH }}
-        echo "COMMIT_ID=$(cd ${{ github.event.inputs.DEVICE_PATH }} && git rev-parse HEAD)" >> $GITHUB_ENV
+        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}
+        git clone ${{ github.event.inputs.DEVICE_TREE }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}
+        cd ${{ github.event.inputs.DEVICE_PATH }}
+        echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV
 
-    - name: Setup Build Environment
+    - name: Check Manifest Branch
+      uses: haya14busa/action-cond@v1
+      id: fox_branch
+      with:
+        cond: ${{ github.event.inputs.MANIFEST_BRANCH == '11.0' || github.event.inputs.MANIFEST_BRANCH == '12.1' }}
+        if_true: lunch twrp_${{ github.event.inputs.DEVICE_NAME }}-eng && make clean && mka adbd ${{ github.event.inputs.BUILD_TARGET }}image
+        if_false: lunch omni_${{ github.event.inputs.DEVICE_NAME }}-eng && make clean && mka ${{ github.event.inputs.BUILD_TARGET }}image
+      
+    - name: Building OrangeFox
       run: |
-        cd OrangeFox
+        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}
+        set +e
         source build/envsetup.sh
         export ALLOW_MISSING_DEPENDENCIES=true
-        lunch twrp_${{ github.event.inputs.DEVICE_NAME }}-eng
+        set -e
+        ${{ steps.fox_branch.outputs.value }}
 
-    - name: Build Recovery
+    - name: Set Build Date # Output will be use in Release
       run: |
-        cd OrangeFox
-        mka ${{ github.event.inputs.BUILD_TARGET }}image 2>&1 | tee build.log
+        echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
 
-    - name: Locate and Verify Artifacts
+    - name: Check if Recovery Exist
       run: |
-        cd OrangeFox/out/target/product/${{ github.event.inputs.DEVICE_NAME }}
-        
-        if [ -f recovery.img ]; then
-          echo "CHECK_IMG_IS_OK=true" >> $GITHUB_ENV
-          echo "FILE_PATH=$(pwd)" >> $GITHUB_ENV
-          echo "RECOVERY_NAME=OrangeFox_${{ github.event.inputs.DEVICE_NAME }}_${{ env.BUILD_DATE }}.img" >> $GITHUB_ENV
-          mv recovery.img ${{ env.RECOVERY_NAME }}
-          md5sum ${{ env.RECOVERY_NAME }} | cut -d ' ' -f1 > ${{ env.RECOVERY_NAME }}.md5
+        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}
+        if [ -f out/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox*.img ]; then
+            echo "CHECK_IMG_IS_OK=true" >> $GITHUB_ENV
+            echo "FILE_PATH=${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}" >> $GITHUB_ENV
+            echo "MD5_IMG=$(md5sum out/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox*.img | cut -d ' ' -f 1)" >> $GITHUB_ENV
+        elif [ -f out/target/product/${{ github.event.inputs.DEVICE_NAME }}/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox*.img ]; then
+            echo "CHECK_IMG_IS_OK=true" >> $GITHUB_ENV
+            echo "FILE_PATH=${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/target/product/${{ github.event.inputs.DEVICE_NAME }}" >> $GITHUB_ENV
+            echo "MD5_IMG=$(md5sum out/target/product/${{ github.event.inputs.DEVICE_NAME }}/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox*.img | cut -d ' ' -f 1)" >> $GITHUB_ENV
         else
-          echo "::error::Recovery image not found in output directory"
-          exit 1
+            echo "Recovery out directory is empty."
+            cd Exit
         fi
 
-    - name: Upload Artifacts
-      uses: actions/upload-artifact@v3
-      if: success()
-      with:
-        name: OrangeFox-${{ github.event.inputs.DEVICE_NAME }}-${{ env.BUILD_DATE }}
-        path: |
-          ${{ env.FILE_PATH }}/${{ env.RECOVERY_NAME }}
-          ${{ env.FILE_PATH }}/${{ env.RECOVERY_NAME }}.md5
+    - name: Rename the Recovery
+      run: |
+        cd ${{ env.FILE_PATH }}/
+        if [ "${{ github.event.inputs.BUILD_TARGET }}" = "boot" ]; then
+        mv OrangeFox*.img boot.img
+        echo "RECOVERY_TYPE=boot" >> $GITHUB_ENV
+        echo "boot.img file found!"
+        elif [ "${{ github.event.inputs.BUILD_TARGET }}" = "recovery" ]; then
+        mv OrangeFox*.img recovery.img
+        echo "RECOVERY_TYPE=recovery" >> $GITHUB_ENV
+        echo "recovery.img file found!"
+        elif [ "${{ github.event.inputs.BUILD_TARGET }}" = "vendorboot" ]; then
+        mv OrangeFox*.img vendor_boot.img
+        echo "RECOVERY_TYPE=vendor_boot" >> $GITHUB_ENV
+        echo "vendor_boot.img file found!"
+        else
+        echo "No Recovery file found!"
+        fi
+      continue-on-error: true
+      
+    - name: Include Recovery Installer
+      run: |
+        if [ ${{ github.event.inputs.RECOVERY_INSTALLER }} = true ]; then
+          cd ${{ env.FILE_PATH }}/
+          wget https://github.com/kinguser981/recovery-installer/releases/download/11256427880/recovery-installer.zip
+          zip -ur recovery-installer.zip ${{ env.RECOVERY_TYPE }}.img
+        fi
+      continue-on-error: true
+        
+    - name: Recovery to tar for Samsung devices
+      run: |
+        if [ ${{ github.event.inputs.RECOVERY_TAR }} = true ]; then
+          cd ${{ env.FILE_PATH }}/
+          tar -cvf ${{ env.RECOVERY_TYPE }}.tar ${{ env.RECOVERY_TYPE }}.img
+        fi
+      continue-on-error: true
 
-    - name: Create Release
+    - name: Upload to Release
+      if: env.CHECK_IMG_IS_OK == 'true'
       uses: softprops/action-gh-release@v1
-      if: success()
       with:
         files: |
-          ${{ env.FILE_PATH }}/${{ env.RECOVERY_NAME }}
-          ${{ env.FILE_PATH }}/${{ env.RECOVERY_NAME }}.md5
-        tag_name: ofox-${{ github.event.inputs.DEVICE_NAME }}-${{ env.BUILD_DATE }}
-        name: OrangeFox ${{ github.event.inputs.MANIFEST_BRANCH }} for ${{ github.event.inputs.DEVICE_NAME }}
+          ${{ env.FILE_PATH }}/${{ env.RECOVERY_TYPE }}.img
+          ${{ env.FILE_PATH }}/${{ env.RECOVERY_TYPE }}.tar
+          ${{ env.FILE_PATH }}/recovery-installer.zip
+          ${{ env.FILE_PATH }}/OrangeFox*.zip
+        name: Unofficial OrangeFox for ${{ github.event.inputs.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
+        tag_name: ${{ github.run_id }}
         body: |
-          ### Build Details
-          - **Device:** ${{ github.event.inputs.DEVICE_NAME }}
-          - **Branch:** ${{ github.event.inputs.MANIFEST_BRANCH }}
-          - **Build Date:** ${{ env.BUILD_DATE }}
-          - **Commit ID:** ${{ env.COMMIT_ID }}
+          Build: ${{ github.event.inputs.MANIFEST_BRANCH }}
+          Device: [Device Tree/Branch](${{ github.event.inputs.DEVICE_TREE }}/tree/${{ github.event.inputs.DEVICE_TREE_BRANCH }})
+          Commit: Most recent [commit](${{ github.event.inputs.DEVICE_TREE }}/commit/${{ env.COMMIT_ID }}) during building.
+          
+    - name: Release ramdisk-recovery
+      if: env.CHECK_IMG_IS_OK == 'true'
+      uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
+      with:
+        files: |
+          ${{ env.FILE_PATH }}/obj/PACKAGING/vendor_ramdisk_fragments_intermediates/recovery.*
+          ${{ env.FILE_PATH }}/ramdisk-recovery.*
+        name: Unofficial OrangeFox for ${{ github.event.inputs.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
+        tag_name: ${{ github.run_id }}
+        body: |
+          Target: ${{ env.RECOVERY_TYPE }}.img
+          Build: ${{ github.event.inputs.MANIFEST_BRANCH }}
+          Device: [Device Tree/Branch](${{ github.event.inputs.DEVICE_TREE }}/tree/${{ github.event.inputs.DEVICE_TREE_BRANCH }})
+          Commit: Most recent [commit](${{ github.event.inputs.DEVICE_TREE }}/commit/${{ env.COMMIT_ID }}) during building.
+          MD5 (img): ${{ env.MD5_IMG }}
+          
+    - name: Run LDCheck
+      run: |
+        cd tools
+        mv -n libneeds ${{ env.FILE_PATH }}/recovery/root/
+        mv -n ldcheck ${{ env.FILE_PATH }}/recovery/root/
+        cd ${{ env.FILE_PATH }}/recovery/root/
+        python3 ldcheck -p system/lib64:vendor/lib64:system/lib:vendor/lib -d ${{ github.event.inputs.LDCHECK }}
+        echo "Done checking missing dependencies. Review, and reconfigure your tree."
+      continue-on-error: true
